name: Build and push docker images
on:
  release:
    types: [published, edited]
  push:
    branches:
      - master 
env:
  IMAGE_NAME: smf-spf
jobs:
  build-image:
    name: Build the image
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        name: Checkout the code
      
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: underspell/$IMAGE_NAME
          tags: v1, latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
